---
- name: Setup ASReview Optuna Environment
  hosts: all
  become: yes
  vars:
    repo_url: "https://github.com/asreview/asreview-optuna.git"
    repo_dir: "asreview-optuna/asreview2-optuna"
    branch_name: "{{ branch_name }}"  # Passed via --extra-vars
    db_uri: "{{ db_uri }}"            # Passed via --extra-vars

  tasks:

    - name: Ensure the system is updated
      apt:
        update_cache: yes
        upgrade: dist

    - name: Reboot the system
      reboot:
        msg: "Rebooting after upgrade"
        connect_timeout: 30

    - name: Wait for system to come back online
      wait_for_connection:
        timeout: 300

    - name: Clone the repository
      git:
        repo: "{{ repo_url }}"
        dest: "/home/{{ ansible_user }}/"
        update: yes
        version: "{{ branch_name }}"
      become: no

    - name: Install python3.12-venv
      apt:
        name: python3.12-venv
        state: present

    - name: Create Python virtual environment
      shell: "python3 -m venv .venv"
      args:
        chdir: "/home/{{ ansible_user }}/{{ repo_dir }}"
      become: no

    - name: Activate virtual environment and install requirements
      shell: |
        source .venv/bin/activate
        pip3 install -r requirements.txt
      args:
        chdir: "/home/{{ ansible_user }}/{{ repo_dir }}"
      become: no

    - name: Create a tmux session for Optuna
      shell: |
        tmux new -d -s optuna "bash -c 'export DB_URI={{ db_uri }} && source .venv/bin/activate && python3 main.py'"
      args:
        chdir: "/home/{{ ansible_user }}/{{ repo_dir }}"
      become: no

    - name: Display setup completion message
      debug:
        msg: "ASReview Optuna environment is set up. Use 'tmux attach -t optuna' to manage the Optuna session."
